# Generated by Django 4.2.7 on 2023-11-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0003_snippet_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
