# Generated by Django 4.2.7 on 2023-11-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet3',
        ),
    ]
