# Generated by Django 4.2.7 on 2023-11-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_snippetv1_snippetv2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='owner',
        ),
        migrations.DeleteModel(
            name='SnippetV1',
        ),
        migrations.DeleteModel(
            name='SnippetV2',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
